<template>
  <v-main>
    <v-container
      class="fill-height"
      fluid
    >
      <v-row
        align="center"
        justify="center"
      >
        <v-col
          cols="12"
          sm="8"
          md="4"
        >
          <v-card class="elevation-12">
            <v-toolbar
              color="primary"
              dark
              flat
            >
              <v-toolbar-title>登錄介面</v-toolbar-title>
            </v-toolbar>
            <v-card-text>
              <v-form
                id="loginForm"
                method="POST"
                action="../back-end/simulation-login"
              >
                <v-text-field
                  v-model="name"
                  :counter="10"
                  label="name"
                  name="name"
                  required
                />
                <v-select
                  v-model="classv"
                  :items="['A','B','C']"
                  name="class"
                  label="Class"
                />
              </v-form>
            </v-card-text>
            <v-card-actions>
              <v-spacer />
              <v-btn
                type="submit"
                form="loginForm"
                color="primary"
                @click="submit"
              >
                登錄
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </v-main>
</template>